= Pflichtenheft VR Escaperoom
// Metadata
feichtinger sarah
1.3, 2020-03-17
:sourcedir: ../src/main/java
:icons: font
:toc: left

== CLD

[plantuml]
----
@startuml
class KesselController {
    book: RecipeBook
}
class RecipeBook {
    recipes: List<Recipe>
}
class Recipe {
    ingredients: List<Ingredient>
    input: Event
}
class Ingredient {
    o: UnityObject
}
class Event {
    e: UnityEvent
}


KesselController "1" -right- "1" RecipeBook
RecipeBook "1" -right- "*" Recipe
Recipe "1" -right- "*" Ingredient
Recipe "1" -down- "1" Event
@enduml
----

== Beschreibung der Ausgangssituation

Escaperooms sind ein unterhaltsames und innovatives Unterhaltungskonzept. Die Teilnehmer sind in einem Themenraum eingeschlossen und müssen Rätsel lösen und Aufgaben meistern, um aus dem Raum zu entkommen.
Für die Umsetzung von Escaperooms benötigen die Betreiber passende Räumlichkeiten, Ausstattung und komplexe Technik.

== Istzustand

Die HTL verfügt nicht über Räumlichkeiten und Einrichtung, um einen realen Escaperoom zu betreiben, möchte aber ein Adventure 
Game beim Tag der offenen Tür und ähnlichen Veranstaltungen präsentieren können.

== Problemstellung

Als Alternative zu den realen, aufwendig zu betreibenden Escaperooms soll eine VR Version kreiert werden, welche kostengünstig
und einfach handhabbar ist, sowie geringe Ansprüche an Hardware und Räumlichkeiten stellt.

== Aufgabenstellung

* Die für die Aufgabenstellung passenden Entwicklungsumgebungen und Tools auswählen
* Das Projektteam muss sich in Software und Hardware Tools einarbeiten
* Spielszenario konzipieren
* Die virtuelle Einrichtung des Raumes aus fertigen (frei verfügbar aus dem Internet) und individuellen (selbst kreierten) Modulen erstellen
* Spielszenario implementieren

=== Funktionale Anforderungen

==== Anwendungsfalldiagramm (Use-Case-Diagram)

[plantuml]
----
    left to right direction
    actor Player
    rectangle {
     Player -- (Entkommen aus dem Raum)
    (Bewegen im Raum) .>(Entkommen aus dem Raum) :<<extend>>
    (Hantieren mit Gegenständen) .>(Entkommen aus dem Raum) :<<extend>>
    (Regeln implementieren) .>(Entkommen aus dem Raum) :<<extend>>
    (Umgebung gestalten) .>(Entkommen aus dem Raum) :<<extend>>

    }
----

==== Use-Case 1

===== Charakterisierende Informationen Use-Case 1

[cols=2]
|===
| Übergeordneter elementarer Geschäftsprozess:
| Schulunterricht

| Ziel des Use Cases:
| Ziel ist es aus dem Raum zu entkommen

| Umgebende Systemgrenze:
| Zur Zielerreichung gibt es als Limit nur eine zeitliche Begrenzung, andere Kriterien wie etwa das Erreichen einer bestimmten Punktezahl sind nicht erforderlich

| Vorbedingung:
| Der Spieler muss alle Rätsel lösen und einen Trank brauen um an den Haustürschlüssel, welcher das Verlassen des Hauses ermöglicht, zu gelangen

| Beteiligte Nutzer:
| Interessierte Schüler am Tag der offenen Tür,
Klassenkollegen,
Evtl. Masters of Escape OG

| Auslösendes Ereignis:
| Auftragserteilung durch Herr Professor Stütz
|===

=== Nicht-funktionale Anforderungen

Typen von Produktcharakteristiken

Typ USE: Benutzbarkeitsanforderung

Das Programm soll selbsterklärend funktionieren und einfach zu bedienen sein.
Sich davor eine Anleitung oder Ähnliches durchzulesen sollte nicht notwendig sein.

Typ PFLEGE: Wartbarkeits- und Portierbarkeitsanforderung

Das Produkt soll später auch in englischer Sprache verfügbar sein.
Außerdem sollten die verschiedenen, aus dem Internet verwendeten 3D-Objekte, wie z.B. Einrichtungsgegenstände später einfach durch selbst designte ersetzbar sein.

Typ SICHER: Sicherheitsanforderung

Das System muss gewährleisten, dass sich der Spieler beim Verwenden nicht verletzt.

Typ LEGAL: Gesetzliche Anforderung

Bei der Verwendung von Objekten aus dem Internet muss darauf geachtet werden, ob und welche Lizenzbedingungen eingehalten werden müssen.

== Zielsetzung

Ziel ist es, eine kostengünstige Alternative zu den teuren und aufwendig zu betreibenden, realen Escaperooms zu schaffen.

== Mengengerüst

Für das Spiel wird eine Oculus Vr Brille, die VR Escaperoom Software und ein Computer mit mindestens:

* NVIDIA GTX 960 oder AMD 290 Grafikkarte
* 1 USB-3.0-Anschluss und 2 USB-2.0-Anschlüssen
* 1 HDMI-1.3-Port
* Intel i3-6100 oder AMD FX4350 Prozessor
* 8 GByte RAM
* einem Betriebssystem ab Windows 7 mit SP1

benötigt.

Die optimalen PC Anforderungen finden Sie unter: https://praxistipps.chip.de/oculus-rift-systemanforderungen-fuer-pc_41200

== Organisatorische "Organisatorische Rahmenbedigungen"

=== Gantt Diagramm

[plantuml,gantt-protoype,png]
----
@startgantt
project starts the 2020/03/27
[Rezepte Erfinden] lasts 3 days
[Grundspielprinzip] lasts 3 days
[Spielprinzip mit Zutaten] lasts 25 days
[Haus bauen] lasts 38 days
[Rätsel einbauen] lasts 38 days
[Zutaten Design] lasts 22 days
[Inneneinrichtung] lasts 44 days
[Verbesserungen/Deteils] lasts 5 days


[Rezepte Erfinden] starts on 2020/03/19
[Verbesserungen/Deteils] starts on 2020/06/01
[Spielprinzip mit Zutaten] starts at [Grundspielprinzip]'s end
[Inneneinrichtung] starts at [Zutaten Design]'s end
[Haus bauen] starts at [Spielprinzip mit Zutaten]'s end
[Rätsel einbauen] starts at [Spielprinzip mit Zutaten]'s end

[Rezepte Erfinden] is colored in Fuchsia/FireBrick
[Grundspielprinzip] is colored in FireBrick/Coral
[Spielprinzip mit Zutaten] is colored in Lavender/LightBlue
[Haus bauen] is colored in Lavender/LightBlue
[Rätsel einbauen] is colored in Lavender/LightBlue
[Verbesserungen/Deteils] is colored in Lavender/LightBlue
@endgantt
----

blau: Allgemein,
pink: Sarah,
rot: Felix,
grün: Daniela