= Pflichtenheft VR Escaperoom
// Metadata
firstname lastname <mail@mail-server>
1.1, 05.02.2020

// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: src/main/java/at/htl/jdbcprimer
:sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: {revnumber} +
Version Date: {revdate} +
Author: Sarah Feichtinger feichtinger.sarah5@gmail.com

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

== Beschreibung der Ausgangssituation

Escaperooms sind ein unterhaltsames und innovatives Unterhaltungskonzept. Die Teilnehmer sind in einem Themenraum eingeschlossen und müssen Rätsel lösen und Aufgaben meistern, um aus dem Raum zu entkommen.
Für die Umsetzung von Escaperooms benötigen die Betreiber passende Räumlichkeiten, Ausstattung und komplexe Technik.

== Istzustand

Die HTL verfügt nicht über Räumlichkeiten und Einrichtung, um einen realen Escaperoom zu betreiben, möchte aber ein Adventure 
Game beim Tag der offenen Tür und ähnlichen Veranstaltungen präsentieren können.

== Problemstellung

Als Alternative zu den realen, aufwendig zu betreibenden Escaperooms soll eine VR Version kreiert werden, welche kostengünstig
und einfach handhabbar ist, sowie geringe Ansprüche an Hardware und Räumlichkeiten stellt.

== Aufgabenstellung

* Die für die Aufgabenstellung passenden Entwicklungsumgebungen und Tools auswählen
* Das Projektteam muss sich in Software und Hardware Tools einarbeiten
* Spielszenario konzipieren
* Die virtuelle Einrichtung des Raumes aus fertigen (frei verfügbar aus dem Internet) und individuellen (selbst kreierten) Modulen erstellen
* Spielszenario implementieren

=== Funktionale Anforderungen

==== Anwendungsfalldiagramm (Use-Case-Diagram)

[plantuml]
----
    left to right direction
    actor Player
    rectangle {
     Player -- (Entkommen aus \ndem Raum)
    }
----

==== Use-Case 1

===== Charakterisierende Informationen Use-Case 1

[cols=2]
|===
| Übergeordneter elementarer Geschäftsprozess:
| Schulunterricht

| Ziel des Use Cases:
| Ziel ist es aus dem Raum zu entkommen

| Umgebende Systemgrenze:
| Zur Zielerreichung gibt es als Limit nur eine zeitliche Begrenzung, andere Kriterien wie etwa das Erreichen einer bestimmten Punktezahl sind nicht erforderlich

| Vorbedingung:
| Der Spieler muss alle Rätsel lösen und einen Trank brauen um an den Haustürschlüssel, welcher das Verlassen des Hauses ermöglicht, zu gelangen

| Beteiligte Nutzer:
| Interessierte Schüler am Tag der offenen Tür,
Klassenkollegen,
Evtl. Masters of Escape OG

| Auslösendes Ereignis:
| Auftragserteilung durch Herr Professor Stütz
|===

=== Nicht-funktionale Anforderungen

Typen von Produktcharakteristiken

Typ USE: Benutzbarkeitsanforderung

Das Programm soll selbsterklärend funktionieren und einfach zu bedienen sein.
Sich davor eine Anleitung oder Ähnliches durchzulesen sollte nicht notwendig sein.

Typ PFLEGE: Wartbarkeits- und Portierbarkeitsanforderung

Das Produkt soll später auch in englischer Sprache verfügbar sein.
Außerdem sollten die verschiedenen, aus dem Internet verwendeten 3D-Objekte, wie z.B. Einrichtungsgegenstände später einfach durch selbst designte ersetzbar sein.

Typ SICHER: Sicherheitsanforderung

Das System muss gewährleisten, dass sich der Spieler beim Verwenden nicht verletzt.

Typ LEGAL: Gesetzliche Anforderung

Bei der Verwendung von Objekten aus dem Internet muss darauf geachtet werden, ob und welche Lizenzbedingungen eingehalten werden müssen.

== Zielsetzung

Ziel ist es, eine kostengünstige Alternative zu den teuren und aufwendig zu betreibenden, realen Escaperooms zu schaffen.

== Mengengerüst

Für das Spiel wird eine Oculus Vr Brille, die VR Escaperoom Software und ein Computer mit mindestens:

* NVIDIA GTX 960 oder AMD 290 Grafikkarte
* 1 USB-3.0-Anschluss und 2 USB-2.0-Anschlüssen
* 1 HDMI-1.3-Port
* Intel i3-6100 oder AMD FX4350 Prozessor
* 8 GByte RAM
* einem Betriebssystem ab Windows 7 mit SP1

benötigt.

Die optimalen PC Anforderungen finden Sie unter: https://praxistipps.chip.de/oculus-rift-systemanforderungen-fuer-pc_41200
