= VR Escape Room Projektantrag
:icons: font
:iconfont-cdn: //maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css

== Anwendungsfalldiagramm

[plantuml]
----
left to right direction
actor Player
rectangle {

  Player -- (Entkommen aus \ndem Raum)


}
----
== Projektantrag
== Escape Room VR
=== 10.10.2019
Syt 2019/20, Version 1.0
Projekt-Bezeichnung: Escape Room VR
Projektauftraggeber: HTL Leonding

==== Projekthintergrund:

Wir wollen eine VR Erfahrung erschaffen, unsere Idee ist es deshalb, einen virtuellen Escape Room zu kreieren.

==== Projektendergebnis:

Am Ende sollte man in einem VR Escape Room (mit Okulus Brille) 5 verschiedene Rätsel lösen müssen, um den Schlüssel für den Ausgang zu erhalten.

==== Projektziele:

Das Projektziel ist eine, im Gegensatz zu teuren Escape Rooms, billige VR-Variante zu erschaffen.

==== Projektbeschreibung
Zuerst muss ein Plan erstellt werden, wie der Escape Room aussehen soll und ein Handlungsstrang festgelegt werden. Danach sollten die Figuren mit Blender modeliert und mit Unity der Escape Room erstellt werden.

==== Projektphasen
===== Planung
In der Planung muss die Hintergrundgeschichte geschrieben werden sowie Skizzen zum Escape Room angefertigt werden.
Soll bis 11.11 gemacht werden
===== Kennenlernen der Software
Alle Teammitglieder sollten Unity und Blender grundlegend beherrschen können.
Soll bis 2.12 gemacht werden
==== Fertiger Escape Room
Fertiger Escape Room
Soll bis Juli  gemacht werden

==== Projektressourcen

+ Unity
 0€ 
 + Blender
 0€
 + VR Headset
 500€

==== Projektrisiken
 Risiken sind, das die Projektmitglieder mit der VR-Programmierung überfordert sein könnten

==== Projektteam
. Sarah Feichtinger (Projektleitung)
. Dumfarth Felix
. Daniela Plöchl

